-- MySQL Script generated by MySQL Workbench
-- 05/11/21 10:40:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 3811863_ongolaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 3811863_ongolaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `3811863_ongolaria` DEFAULT CHARACTER SET utf8 ;
USE `3811863_ongolaria` ;

-- -----------------------------------------------------
-- Table `3811863_ongolaria`.`TIPO_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3811863_ongolaria`.`TIPO_USUARIO` (
  `IDTIPO_USUARIO` INT NOT NULL,
  `TIPO` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`IDTIPO_USUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3811863_ongolaria`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3811863_ongolaria`.`USUARIOS` (
  `IDUSUARIOS` INT NOT NULL,
  `PRIMEIRO_NOME` VARCHAR(25) NOT NULL,
  `SOBRE_NOME` VARCHAR(100) NOT NULL,
  `SENHA` VARCHAR(8) NOT NULL,
  `EMAIL` VARCHAR(150) NOT NULL,
  `TIPO_USUARIO_IDTIPO_USUARIO` INT NOT NULL,
  PRIMARY KEY (`IDUSUARIOS`),
  INDEX `fk_USUARIOS_TIPO_USUARIO1_idx` (`TIPO_USUARIO_IDTIPO_USUARIO` ASC),
  CONSTRAINT `fk_USUARIOS_TIPO_USUARIO1`
    FOREIGN KEY (`TIPO_USUARIO_IDTIPO_USUARIO`)
    REFERENCES `3811863_ongolaria`.`TIPO_USUARIO` (`IDTIPO_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3811863_ongolaria`.`TIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3811863_ongolaria`.`TIPO` (
  `IDTIPO` INT NOT NULL,
  `DESCRICAO` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`IDTIPO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3811863_ongolaria`.`CONTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3811863_ongolaria`.`CONTAS` (
  `IDCONTAS` INT NOT NULL,
  `PDF` VARCHAR(100) NOT NULL,
  `TIPO_IDTIPO` INT NOT NULL,
  PRIMARY KEY (`IDCONTAS`),
  INDEX `fk_CONTAS_TIPO_idx` (`TIPO_IDTIPO` ASC),
  CONSTRAINT `fk_CONTAS_TIPO`
    FOREIGN KEY (`TIPO_IDTIPO`)
    REFERENCES `3811863_ongolaria`.`TIPO` (`IDTIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
